### ISSUE TITLE
Use <layername> from .qrl as title

### ISSUE THREAD

**Issue by baffioso** [Septima/qgis-qlrbrowser#28]
Could be handy to use `<layername>` as title in the QRL Browser. Seems like it's using title of the qrl-file at the moment.

**Comment by Frederikssund** [comment]
This is _not_ dead straight simple:
- The plugin has to open and start interpreting the qlr-file to find the layername. This will cause a slowdown in showing the tree
- The qlr file can reference several layers. Which layername should it use ? 
- The qlr file can reference a layergroup or layergroups instead of layers. Which name should it use ?

**Comment by baffioso** [comment]
Wasn't aware that the qrl file can reference multible layers/groups. Maybe a solution could be to check if the qrl holds multible layers or groups. If this is the case: use file name else: use `<layername>`

This might though be a bit of a hassle for a small issue and a bit strange exception regarding the naming.

**Comment by AsgerPetersen** [comment]
I think it is going to be confusing if the browser shows a mix between file names and something else. Conceptually, I think, this is a file browser with some added functionality.

I am going to close the issue. Please reopen it if you disagree with me.
