### ISSUE TITLE
File lock on directories and qlr-files when one or more users actually uses the qlr-browser (bug)

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#36]
The qlr-browser leaves a file lock on the qlr-browser directory and the qlr-files, so it's impossible for administrator to rearrange (move, delete, rename) the directories and files with the windows file-explorer (Danish: stifinder) when one ore more ordinary users has opened QGIS and the qlr-browser.
This is a serious issue. It will make it impossible to rearrange the qlr directory inside normal working hours

**Comment by Frederikssund** [comment]
An update - It seems that it's only _directories_, that locked by the qlr-browser application

**Comment by MieWinstrup** [comment]
Update - the problem with not being able to change the foldernames only occur when a qlr-file is selected in the Qlr Browser. When no file is selected, but Qlr-browser is open, then it is possible to change foldername. When one file in the Qlr-browser is selected and then deselected the lock remains on the folder (and it is still not possible to change the foldername). 

This lock on the folder should not exist in order to allow the administrator to change the name of folders despite some users have the qlr-browser open and a file selected.

**Comment by MieWinstrup** [comment]
Update - the problem with not being able to change the foldernames only occur when a qlr-file is selected in the Qlr Browser. When no file is selected, but Qlr-browser is open, then it is possible to change foldername. When one file in the Qlr-browser is selected and then deselected the lock remains on the folder (and it is still not possible to change the foldername). 

This lock on the folder should not exist in order to allow the administrator to change the name of folders despite some users have the qlr-browser open and a file selected.

**Comment by MieWinstrup** [comment]
Update - the problem with not being able to change the foldernames only occur when a qlr-file is selected in the Qlr Browser. When no file is selected, but Qlr-browser is open, then it is possible to change foldername. When one file in the Qlr-browser is selected and then deselected the lock remains on the folder (and it is still not possible to change the foldername). 

This lock on the folder should not exist in order to allow the administrator to change the name of folders despite some users have the qlr-browser open and a file selected.

**Comment by bsnizek** [comment]
Waiting for Greg to get me a WIN license.

**Comment by AsgerPetersen** [comment]
This is a general QGIS problem. Loading the QLR directly through QGIS menu item "Layer -> Add from layer definition file..." has the samme effect.

I have reported this to the QGIS issue tracker here: http://hub.qgis.org/issues/14811

**Comment by AsgerPetersen** [comment]
I'll see if I can make a work around.

**Comment by AsgerPetersen** [comment]
Work around works around the issue ;-)
