### ISSUE TITLE
Filtered results is shown with full file- and directory names

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#58]
When you use the filter function the resulting directory tree contains full names of files and directories, even if "Hide numeric prefix" check in settings is checked; i.e: If you have a file called "123~yabba.qlr" it will _not_ be shown as "yabba" but as "123~yabba".

The problem is _probably_ caused by the method  "FileSystemItem.filtered" in module core/filesystemmodel.py, lines 83 - 111. There is 3  method instantiations of the "FileSystemItem" object without using the "namingregex" argument.
The  "recursion_counter" argument is missing as well, so the function won't respect the file counter limit.

Regards Bo Victor

**Comment by MieWinstrup** [comment]
@Frederikssund thanks for reporting!

**Comment by MieWinstrup** [comment]
@Frederikssund 
Is it correct that the issue is that if the QLR-browser is configured to hide '01~' and this part of the qlr-name is hidden in the qlr-browser:
![qlr_githubissue58](https://cloud.githubusercontent.com/assets/16276034/26307354/5a436478-3ef4-11e7-93c4-72b2de7f930b.png)

But when using the filtering option, the full qlr-name is shown:
![qlr_githubissue58_2](https://cloud.githubusercontent.com/assets/16276034/26307444/e2afc46e-3ef4-11e7-8d5c-4d27bd2c4d47.png)

**Comment by Frederikssund** [comment]
Hi Mie - 
I assume, you asked me a question. In that case: The answer is "Yes". 
The QLR browser search function does not respect the "Hide numeric prefixes..." choice made by the user
