### ISSUE TITLE
qlr file doesn't show up in QGIS 3.2

### ISSUE THREAD

**Issue by reginaldc** [Septima/qgis-qlrbrowser#75]
Hi,

When I make a qlr file from a shape file and put it in the library using QGIS 3.2, it doesn't show any features when it's loaded. In the layer pane I see the loaded layer without any styling aplied to it.
I compared the qlr file to other qlrfiles that load well I noticed that the path was wrong: 
this works: <datasource>F:\Ingelmunster\ROP\ROP2013.shp</datasource>
this fails: <datasource>../../../Ingelmunster/ROP/2017/36007/36007.shp</datasource>
changing it to <datasource>F:\Ingelmunster/ROP/2017/36007/36007.shp</datasource> makes it work
I have set the project to use absolute paths when I made the qlr files.
Is there a bug in QGIS 3.2 or did some part of the code of qlr-browser change?

Regards,

**Comment by reginaldc** [comment]
Just some more information: 
F:\ is a network drive that is mounted on \\someserver\data\data

**Comment by MieWinstrup** [comment]
Are you able to add the qlr-file to QGIS without using the Qlr-browser?

**Comment by MieWinstrup** [comment]
@reginaldc - Thanks for reporting the issue.

It seems like a change (bug?) in the way QGIS stores qlrfiles in QGIS 3.2: Even though the project settings is changed to absolute paths, this setting is not applied to the qlrfile (as it was in QGIS 2.18).

I have reported this as a bug in QGIS Issue tracker:
https://issues.qgis.org/issues/19672

**Comment by MieWinstrup** [comment]
And this is still a problem with QGIS 3.6.2. Despite changing the path to absolute in the QGIS-project, the paths in a qlr-file are stored with relative paths. This means that QLR-files made with QGIS 3 does not work in the QLR-Browser. The issue needs to be fixed in QGIS before this works again. 

Until then, people will have to create the qlrfiles with QGIS 2.18 - or manually correct the paths in the qlrfile.

The bug with QGIS is reported in the QGIS Issue tracker: https://issues.qgis.org/issues/19672

**Comment by bvthomsen** [comment]
The underlying bug i QGIS : https://github.com/qgis/QGIS/issues/27497 is fixed. I suggest you close this issue
